name: beaver_architect_api
description: "An easier way to build"
publish_to: 'Millenniar'

version: 0.1.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  http: ^1.2.1
  mongo_dart: ^0.10.3
  uuid: any
